import os
import numpy as np
import pandas as pd
from typing import Optional, Dict


def save_dataframe_to_txt(
    df: pd.DataFrame,
    file_path: str,
    depth_col: str = 'DEPTH',
    delimiter: str = '\t',
    float_format: str = '%.6f',
    header: bool = True,
    comments: str = '',
    metadata: Optional[Dict[str, str]] = None,
    encoding: str = 'utf-8',
    index: bool = False
) -> None:
    """
    将 DataFrame 保存为测井格式 TXT 文件

    文件结构:
        1. 注释头（# 开头的元信息行）
        2. 列名行（可选）
        3. 数据主体（按指定精度格式化）

    参数说明见上方接口设计文档。
    """
    # ===================== 1. 参数校验 =====================
    if depth_col is None:
        depth_col = df.columns[0]

    if df is None or df.empty:
        raise ValueError("DataFrame 为空，无法保存")

    if not isinstance(df, pd.DataFrame):
        raise TypeError(f"输入必须是 pandas.DataFrame，当前: {type(df)}")

    # 确保输出目录存在
    out_dir = os.path.dirname(file_path)
    if out_dir and not os.path.exists(out_dir):
        os.makedirs(out_dir, exist_ok=True)
        print(f"[INFO] 自动创建目录: {out_dir}")

    # ===================== 2. 列顺序调整 =====================
    # 把深度列放到第一列（测井行业惯例）
    cols = list(df.columns)
    if depth_col in cols:
        cols = [depth_col] + [c for c in cols if c != depth_col]
        df_out = df[cols].copy()
    else:
        # 深度列不存在时给个警告，但仍继续保存
        print(f"[WARN] 未找到深度列 '{depth_col}'，按原列序保存")
        df_out = df.copy()

    # ===================== 3. 精度格式化 =====================
    # 对浮点列应用格式化字符串，整型/字符列保持不变
    for col in df_out.columns:
        if np.issubdtype(df_out[col].dtype, np.floating):
            df_out[col] = df_out[col].apply(lambda x: float_format % x if pd.notna(x) else x)

    # ===================== 4. 写入文件 =====================
    with open(file_path, 'w', encoding=encoding) as f:
        # 4.1 写入元信息注释头
        f.write(f"{comments} ============================================\n")
        f.write(f"{comments} Well Log Data Export\n")
        f.write(f"{comments} Generated by save_dataframe_to_txt\n")
        f.write(f"{comments} ============================================\n")

        if metadata:
            for k, v in metadata.items():
                f.write(f"{comments} {k}: {v}\n")

        f.write(f"{comments} Columns: {list(df_out.columns)}\n")
        f.write(f"{comments} Rows: {len(df_out)}\n")
        f.write(f"{comments} ============================================\n\n")

    # ===================== 5. 输出摘要 =====================
    file_size = os.path.getsize(file_path) / 1024  # KB
    print(f"[INFO] 文件已保存: {file_path}")
    print(f"[INFO] 文件大小: {file_size:.2f} KB")
    print(f"[INFO] 数据维度: {df_out.shape[0]} 行 × {df_out.shape[1]} 列")
    print(f"[INFO] 列顺序: {list(df_out.columns)}")
    print(f"[INFO] 精度格式: {float_format}")
    print(f"[INFO] 分隔符: {repr(delimiter)}")